// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO projects.api_keys (project_id, user_id, key_hash, label)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, user_id, key_hash, label, created_at, updated_at, revoked_at, deleted_at
`

type CreateAPIKeyParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
	KeyHash   string      `json:"key_hash"`
	Label     *string     `json:"label"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ProjectsApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ProjectID,
		arg.UserID,
		arg.KeyHash,
		arg.Label,
	)
	var i ProjectsApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.KeyHash,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, project_id, user_id, key_hash, label, created_at, updated_at, revoked_at, deleted_at
FROM projects.api_keys
WHERE key_hash = $1
  AND revoked_at IS NULL
  AND deleted_at IS NULL
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ProjectsApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ProjectsApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.KeyHash,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAPIKeysByProjectID = `-- name: ListAPIKeysByProjectID :many
SELECT id, project_id, user_id, key_hash, label, created_at, updated_at, revoked_at, deleted_at
FROM projects.api_keys
WHERE project_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByProjectID(ctx context.Context, projectID pgtype.UUID) ([]ProjectsApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectsApiKey
	for rows.Next() {
		var i ProjectsApiKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.KeyHash,
			&i.Label,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RevokedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE projects.api_keys
SET revoked_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND project_id = $2
  AND revoked_at IS NULL
  AND deleted_at IS NULL
`

type RevokeAPIKeyParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.ProjectID)
	return err
}
