// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blogs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBlog = `-- name: CreateBlog :one
INSERT INTO projects.blogs (project_id, title, slug, content, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, title, slug, content, status, cover_image_url, seo_title, seo_description, created_at, updated_at, published_at, deleted_at
`

type CreateBlogParams struct {
	ProjectID pgtype.UUID        `json:"project_id"`
	Title     string             `json:"title"`
	Slug      string             `json:"slug"`
	Content   string             `json:"content"`
	Status    ProjectsBlogStatus `json:"status"`
}

func (q *Queries) CreateBlog(ctx context.Context, arg CreateBlogParams) (ProjectsBlog, error) {
	row := q.db.QueryRow(ctx, createBlog,
		arg.ProjectID,
		arg.Title,
		arg.Slug,
		arg.Content,
		arg.Status,
	)
	var i ProjectsBlog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Status,
		&i.CoverImageUrl,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBlogByID = `-- name: GetBlogByID :one
SELECT id, project_id, title, slug, content, status, cover_image_url, seo_title, seo_description, created_at, updated_at, published_at, deleted_at
FROM projects.blogs
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetBlogByID(ctx context.Context, id pgtype.UUID) (ProjectsBlog, error) {
	row := q.db.QueryRow(ctx, getBlogByID, id)
	var i ProjectsBlog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Status,
		&i.CoverImageUrl,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBlogByProjectAndSlug = `-- name: GetBlogByProjectAndSlug :one
SELECT id, project_id, title, slug, content, status, cover_image_url, seo_title, seo_description, created_at, updated_at, published_at, deleted_at
FROM projects.blogs
WHERE project_id = $1
  AND slug = $2
  AND deleted_at IS NULL
`

type GetBlogByProjectAndSlugParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Slug      string      `json:"slug"`
}

func (q *Queries) GetBlogByProjectAndSlug(ctx context.Context, arg GetBlogByProjectAndSlugParams) (ProjectsBlog, error) {
	row := q.db.QueryRow(ctx, getBlogByProjectAndSlug, arg.ProjectID, arg.Slug)
	var i ProjectsBlog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Status,
		&i.CoverImageUrl,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPublishedBlogByProjectAndSlug = `-- name: GetPublishedBlogByProjectAndSlug :one
SELECT id, project_id, title, slug, content, status, cover_image_url, seo_title, seo_description, created_at, updated_at, published_at, deleted_at
FROM projects.blogs
WHERE project_id = $1
  AND slug = $2
  AND status = 'published'
  AND deleted_at IS NULL
`

type GetPublishedBlogByProjectAndSlugParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Slug      string      `json:"slug"`
}

func (q *Queries) GetPublishedBlogByProjectAndSlug(ctx context.Context, arg GetPublishedBlogByProjectAndSlugParams) (ProjectsBlog, error) {
	row := q.db.QueryRow(ctx, getPublishedBlogByProjectAndSlug, arg.ProjectID, arg.Slug)
	var i ProjectsBlog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Status,
		&i.CoverImageUrl,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listBlogsByProject = `-- name: ListBlogsByProject :many
SELECT id, project_id, title, slug, content, status, cover_image_url, seo_title, seo_description, created_at, updated_at, published_at, deleted_at
FROM projects.blogs
WHERE project_id = $1
  AND deleted_at IS NULL
ORDER BY updated_at DESC
`

func (q *Queries) ListBlogsByProject(ctx context.Context, projectID pgtype.UUID) ([]ProjectsBlog, error) {
	rows, err := q.db.Query(ctx, listBlogsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectsBlog
	for rows.Next() {
		var i ProjectsBlog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.Status,
			&i.CoverImageUrl,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedBlogsByProject = `-- name: ListPublishedBlogsByProject :many
SELECT id, project_id, title, slug, content, status, cover_image_url, seo_title, seo_description, created_at, updated_at, published_at, deleted_at
FROM projects.blogs
WHERE project_id = $1
  AND status = 'published'
  AND deleted_at IS NULL
ORDER BY published_at DESC NULLS LAST, created_at DESC
`

func (q *Queries) ListPublishedBlogsByProject(ctx context.Context, projectID pgtype.UUID) ([]ProjectsBlog, error) {
	rows, err := q.db.Query(ctx, listPublishedBlogsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectsBlog
	for rows.Next() {
		var i ProjectsBlog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.Status,
			&i.CoverImageUrl,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteBlog = `-- name: SoftDeleteBlog :exec
UPDATE projects.blogs
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND project_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteBlogParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) SoftDeleteBlog(ctx context.Context, arg SoftDeleteBlogParams) error {
	_, err := q.db.Exec(ctx, softDeleteBlog, arg.ID, arg.ProjectID)
	return err
}

const updateBlog = `-- name: UpdateBlog :one
UPDATE projects.blogs
SET
    title = $3,
    slug = $4,
    content = $5,
    status = $6,
    cover_image_url = $7,
    seo_title = $8,
    seo_description = $9,
    published_at = $10,
    updated_at = NOW()
WHERE id = $1
  AND project_id = $2
  AND deleted_at IS NULL
RETURNING id, project_id, title, slug, content, status, cover_image_url, seo_title, seo_description, created_at, updated_at, published_at, deleted_at
`

type UpdateBlogParams struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	Title          string             `json:"title"`
	Slug           string             `json:"slug"`
	Content        string             `json:"content"`
	Status         ProjectsBlogStatus `json:"status"`
	CoverImageUrl  *string            `json:"cover_image_url"`
	SeoTitle       *string            `json:"seo_title"`
	SeoDescription *string            `json:"seo_description"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) UpdateBlog(ctx context.Context, arg UpdateBlogParams) (ProjectsBlog, error) {
	row := q.db.QueryRow(ctx, updateBlog,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Slug,
		arg.Content,
		arg.Status,
		arg.CoverImageUrl,
		arg.SeoTitle,
		arg.SeoDescription,
		arg.PublishedAt,
	)
	var i ProjectsBlog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Status,
		&i.CoverImageUrl,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}
