// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO projects.comments (blog_id, parent_id, author_name, author_email, body)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, blog_id, parent_id, author_name, author_email, body, created_at, updated_at
`

type CreateCommentParams struct {
	BlogID      pgtype.UUID `json:"blog_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	AuthorName  string      `json:"author_name"`
	AuthorEmail *string     `json:"author_email"`
	Body        string      `json:"body"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (ProjectsComment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.BlogID,
		arg.ParentID,
		arg.AuthorName,
		arg.AuthorEmail,
		arg.Body,
	)
	var i ProjectsComment
	err := row.Scan(
		&i.ID,
		&i.BlogID,
		&i.ParentID,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM projects.comments
WHERE id = $1
  AND blog_id = $2
`

type DeleteCommentParams struct {
	ID     pgtype.UUID `json:"id"`
	BlogID pgtype.UUID `json:"blog_id"`
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) error {
	_, err := q.db.Exec(ctx, deleteComment, arg.ID, arg.BlogID)
	return err
}

const listCommentsByBlogID = `-- name: ListCommentsByBlogID :many
SELECT id, blog_id, parent_id, author_name, author_email, body, created_at, updated_at
FROM projects.comments
WHERE blog_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListCommentsByBlogID(ctx context.Context, blogID pgtype.UUID) ([]ProjectsComment, error) {
	rows, err := q.db.Query(ctx, listCommentsByBlogID, blogID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectsComment
	for rows.Next() {
		var i ProjectsComment
		if err := rows.Scan(
			&i.ID,
			&i.BlogID,
			&i.ParentID,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
