// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: likes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLikesByBlogID = `-- name: CountLikesByBlogID :one
SELECT COUNT(*)::bigint AS count
FROM projects.likes
WHERE blog_id = $1
`

func (q *Queries) CountLikesByBlogID(ctx context.Context, blogID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLikesByBlogID, blogID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLike = `-- name: CreateLike :one
INSERT INTO projects.likes (blog_id, visitor_hash)
VALUES ($1, $2)
RETURNING id, blog_id, visitor_hash, created_at
`

type CreateLikeParams struct {
	BlogID      pgtype.UUID `json:"blog_id"`
	VisitorHash string      `json:"visitor_hash"`
}

func (q *Queries) CreateLike(ctx context.Context, arg CreateLikeParams) (ProjectsLike, error) {
	row := q.db.QueryRow(ctx, createLike, arg.BlogID, arg.VisitorHash)
	var i ProjectsLike
	err := row.Scan(
		&i.ID,
		&i.BlogID,
		&i.VisitorHash,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLike = `-- name: DeleteLike :exec
DELETE FROM projects.likes
WHERE blog_id = $1
  AND visitor_hash = $2
`

type DeleteLikeParams struct {
	BlogID      pgtype.UUID `json:"blog_id"`
	VisitorHash string      `json:"visitor_hash"`
}

func (q *Queries) DeleteLike(ctx context.Context, arg DeleteLikeParams) error {
	_, err := q.db.Exec(ctx, deleteLike, arg.BlogID, arg.VisitorHash)
	return err
}
