// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ProjectsBlogStatus string

const (
	ProjectsBlogStatusDraft     ProjectsBlogStatus = "draft"
	ProjectsBlogStatusPublished ProjectsBlogStatus = "published"
)

func (e *ProjectsBlogStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectsBlogStatus(s)
	case string:
		*e = ProjectsBlogStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectsBlogStatus: %T", src)
	}
	return nil
}

type NullProjectsBlogStatus struct {
	ProjectsBlogStatus ProjectsBlogStatus `json:"projects_blog_status"`
	Valid              bool               `json:"valid"` // Valid is true if ProjectsBlogStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectsBlogStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectsBlogStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectsBlogStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectsBlogStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectsBlogStatus), nil
}

type ProjectsApiKey struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	KeyHash   string             `json:"key_hash"`
	Label     *string            `json:"label"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type ProjectsBlog struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	Title          string             `json:"title"`
	Slug           string             `json:"slug"`
	Content        string             `json:"content"`
	Status         ProjectsBlogStatus `json:"status"`
	CoverImageUrl  *string            `json:"cover_image_url"`
	SeoTitle       *string            `json:"seo_title"`
	SeoDescription *string            `json:"seo_description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type ProjectsBlogTag struct {
	BlogID    pgtype.UUID `json:"blog_id"`
	TagID     pgtype.UUID `json:"tag_id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

type ProjectsComment struct {
	ID          pgtype.UUID        `json:"id"`
	BlogID      pgtype.UUID        `json:"blog_id"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	AuthorName  string             `json:"author_name"`
	AuthorEmail *string            `json:"author_email"`
	Body        string             `json:"body"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ProjectsLike struct {
	ID          pgtype.UUID        `json:"id"`
	BlogID      pgtype.UUID        `json:"blog_id"`
	VisitorHash string             `json:"visitor_hash"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ProjectsProject struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type ProjectsTag struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UsersUser struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
