// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects.projects (user_id, name, slug)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, slug, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
	Slug   string      `json:"slug"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (ProjectsProject, error) {
	row := q.db.QueryRow(ctx, createProject, arg.UserID, arg.Name, arg.Slug)
	var i ProjectsProject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, user_id, name, slug, created_at, updated_at, deleted_at
FROM projects.projects
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetProjectByID(ctx context.Context, id pgtype.UUID) (ProjectsProject, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i ProjectsProject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, user_id, name, slug, created_at, updated_at, deleted_at
FROM projects.projects
WHERE slug = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (ProjectsProject, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, slug)
	var i ProjectsProject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProjectsByUserID = `-- name: ListProjectsByUserID :many
SELECT id, user_id, name, slug, created_at, updated_at, deleted_at
FROM projects.projects
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListProjectsByUserID(ctx context.Context, userID pgtype.UUID) ([]ProjectsProject, error) {
	rows, err := q.db.Query(ctx, listProjectsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectsProject
	for rows.Next() {
		var i ProjectsProject
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
