// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountLikesByBlogID(ctx context.Context, blogID pgtype.UUID) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ProjectsApiKey, error)
	CreateBlog(ctx context.Context, arg CreateBlogParams) (ProjectsBlog, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (ProjectsComment, error)
	CreateLike(ctx context.Context, arg CreateLikeParams) (ProjectsLike, error)
	CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (UsersOauthAccount, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (ProjectsProject, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (UsersUser, error)
	CreateVisitor(ctx context.Context, arg CreateVisitorParams) (ProjectsVisitor, error)
	DeleteComment(ctx context.Context, arg DeleteCommentParams) error
	DeleteLike(ctx context.Context, arg DeleteLikeParams) error
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ProjectsApiKey, error)
	GetBlogByID(ctx context.Context, id pgtype.UUID) (ProjectsBlog, error)
	GetBlogByProjectAndSlug(ctx context.Context, arg GetBlogByProjectAndSlugParams) (ProjectsBlog, error)
	GetProjectByID(ctx context.Context, id pgtype.UUID) (ProjectsProject, error)
	GetProjectBySlug(ctx context.Context, slug string) (ProjectsProject, error)
	GetPublishedBlogByProjectAndSlug(ctx context.Context, arg GetPublishedBlogByProjectAndSlugParams) (ProjectsBlog, error)
	GetTagByProjectAndSlug(ctx context.Context, arg GetTagByProjectAndSlugParams) (ProjectsTag, error)
	GetUserByEmail(ctx context.Context, email string) (UsersUser, error)
	GetUserByOAuthProvider(ctx context.Context, arg GetUserByOAuthProviderParams) (UsersUser, error)
	GetVisitorByEmail(ctx context.Context, arg GetVisitorByEmailParams) (ProjectsVisitor, error)
	ListAPIKeysByProjectID(ctx context.Context, projectID pgtype.UUID) ([]ProjectsApiKey, error)
	ListBlogsByProject(ctx context.Context, projectID pgtype.UUID) ([]ProjectsBlog, error)
	ListCommentsByBlogID(ctx context.Context, blogID pgtype.UUID) ([]ProjectsComment, error)
	ListProjectsByUserID(ctx context.Context, userID pgtype.UUID) ([]ProjectsProject, error)
	ListPublishedBlogsByProject(ctx context.Context, projectID pgtype.UUID) ([]ProjectsBlog, error)
	ListTagsByProjectID(ctx context.Context, projectID pgtype.UUID) ([]ProjectsTag, error)
	ListTagsForBlog(ctx context.Context, arg ListTagsForBlogParams) ([]ProjectsTag, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error
	SoftDeleteBlog(ctx context.Context, arg SoftDeleteBlogParams) error
	UpdateBlog(ctx context.Context, arg UpdateBlogParams) (ProjectsBlog, error)
	UpsertTag(ctx context.Context, arg UpsertTagParams) (ProjectsTag, error)
}

var _ Querier = (*Queries)(nil)
