// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTagByProjectAndSlug = `-- name: GetTagByProjectAndSlug :one
SELECT id, project_id, name, slug, created_at
FROM projects.tags
WHERE project_id = $1
  AND slug = $2
`

type GetTagByProjectAndSlugParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Slug      string      `json:"slug"`
}

func (q *Queries) GetTagByProjectAndSlug(ctx context.Context, arg GetTagByProjectAndSlugParams) (ProjectsTag, error) {
	row := q.db.QueryRow(ctx, getTagByProjectAndSlug, arg.ProjectID, arg.Slug)
	var i ProjectsTag
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const listTagsByProjectID = `-- name: ListTagsByProjectID :many
SELECT id, project_id, name, slug, created_at
FROM projects.tags
WHERE project_id = $1
ORDER BY name ASC
`

func (q *Queries) ListTagsByProjectID(ctx context.Context, projectID pgtype.UUID) ([]ProjectsTag, error) {
	rows, err := q.db.Query(ctx, listTagsByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectsTag
	for rows.Next() {
		var i ProjectsTag
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForBlog = `-- name: ListTagsForBlog :many
SELECT t.id, t.project_id, t.name, t.slug, t.created_at
FROM projects.tags t
INNER JOIN projects.blog_tags bt ON bt.tag_id = t.id AND bt.project_id = t.project_id
WHERE bt.blog_id = $1
  AND bt.project_id = $2
ORDER BY t.name ASC
`

type ListTagsForBlogParams struct {
	BlogID    pgtype.UUID `json:"blog_id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) ListTagsForBlog(ctx context.Context, arg ListTagsForBlogParams) ([]ProjectsTag, error) {
	rows, err := q.db.Query(ctx, listTagsForBlog, arg.BlogID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectsTag
	for rows.Next() {
		var i ProjectsTag
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO projects.tags (project_id, name, slug)
VALUES ($1, $2, $3)
ON CONFLICT (project_id, slug) DO UPDATE
SET name = EXCLUDED.name
RETURNING id, project_id, name, slug, created_at
`

type UpsertTagParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
	Slug      string      `json:"slug"`
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (ProjectsTag, error) {
	row := q.db.QueryRow(ctx, upsertTag, arg.ProjectID, arg.Name, arg.Slug)
	var i ProjectsTag
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}
